### ISSUE TITLE
Citing this package for reference.

### ISSUE THREAD

**Issue by GillesJ** [LSYS/LexicalRichness#1]
Dear maintainer,
I am using this package in my research and was wondering how to cite it.

Can you confirm if the citation (mainly the author's name) is correct?
```
@misc{lexicalrichnesspythongithub,
  author = {Shen Yan Shun},
  title = {LexicalRichness Python module},
  year = {2019},
  version = {0.1.3.}
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/LSYS/LexicalRichness}},
  commit = {22ad88f87b83892862413cc2e889b8ceb7b2eab1}
}
```
May I also suggest adding this bibtex entry to the README?

Thank you kindly for making this package!

**Comment by LSYS** [comment]
Hi Gilles

Thank you for reaching out to me. Yeap the citation seems about right. Shen
is my family name, while Yan Shun is my given name. I sometimes use Lucas
as well because people have problem with the Chinese names.

Also thanks for highlighting this, I use open source packages myself for my
research but didn't think to cite them as a typical bibtex item (up to now
I just mention the name of the package and include a link to the repo).

Hope the package is helpful and bugfree.
Lucas

**Comment by GillesJ** [comment]
Thanks, Yan Shun!
So a correct first-lastname (Western-style) bibtex entry is:
```
@misc{lexicalrichnesspythongithub,
  author = {Yan Shun Shen},
  title = {LexicalRichness Python module},
  year = {2019},
  version = {0.1.3.}
  publisher = {GitHub},
  journal = {GitHub repository},
  howpublished = {\url{https://github.com/LSYS/LexicalRichness}},
  commit = {22ad88f87b83892862413cc2e889b8ceb7b2eab1}
}
```

**Comment by LSYS** [comment]
yeap
